name: build-full-jar
on:
  push:
    branches: [main]
jobs:
  clone-code:
    name: 拉取代码
    runs-on: ubuntu-latest
    steps:
      - name: 拉取前台代码
        run: |
          git clone --depth 1 https://github.com/wrote-code/media-ui.git
      - name: 设置node环境
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
          cache: yarn
          cache-dependency-path: media-ui/yarn.lock
      - name: 拉取后台代码
        run: |
          git clone --depth 1 https://github.com/wrote-code/media.git
      - name: 设置java环境
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven

  build-react:
    name: 编译前台代码
    runs-on: ubuntu-latest
    needs: clone-code
    steps:
      - name: 编译前台代码
        run: |
          cd media-ui
          node -v
          npm -v
          yarn -v
          yarn install
          yarn build
  build-java:
    name: 编译后台代码
    runs-on: ubuntu-latest
    needs: [clone-code, build-react]
    steps:
      - name: 编译后台代码
        run: |
          cd media
          mkdir src/main/resources/static
          cp -r ../media-ui/dist src/main/resources/static
          mvn -v
          java -version
          mvn -B clean
          mvn -DskipTests=true -B package
  upload-jar:
    name: 上传制品
    runs-on: ubuntu-latest
    needs: [clone-code, build-react, build-java]
    steps:
      - name: 上传完整制品
        uses: actions/upload-artifact@v3
        with:
          name: 可执行jar包
          path: media/target/media-*.jar
